name: Basic build and test

env:
  MANDREL_VERSION: "22.3.0.1-Final"
  MANDREL_IMAGE: "quay.io/quarkus/ubi-quarkus-mandrel"

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  jvm-build-test:
    runs-on: ubuntu-latest
    if: github.repository == 'edeandrea/how-about-some-tests'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: build-test-jvm
        run: ./mvnw -B clean verify -Dquarkus.http.host=0.0.0.0

  jvm-container-build-test:
    runs-on: ubuntu-latest
    if: github.repository == 'edeandrea/how-about-some-tests'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: build-test-jvm-container
        run: ./mvnw -B clean verify -Dquarkus.http.host=0.0.0.0 -Dquarkus.container-image.build=true

  native-build-test:
    runs-on: ubuntu-latest
    if: github.repository == 'edeandrea/how-about-some-tests'
    steps:
      - uses: actions/checkout@v4

      - name: Cache and restore Mandrel distro
        id: check-mandrel-cache
        uses: actions/cache@v3
        with:
          path: mandrel-${{ env.MANDREL_VERSION }}-17.tar.gz
          key: mandrel-distro-${{ env.MANDREL_VERSION }}-17

      - name: Download Mandrel
        if: steps.check-mandrel-cache.outputs.cache-hit != 'true'
        run: |
          download_url="https://github.com/graalvm/mandrel/releases/download/mandrel-${MANDREL_VERSION}/mandrel-java17-linux-amd64-${MANDREL_VERSION}.tar.gz"
          wget -q -O mandrel-${{ env.MANDREL_VERSION }}-17.tar.gz $download_url
          
      - name: Setup Maven+OpenJDK Distro
        uses: actions/setup-java@v3
        with:
          distribution: jdkfile
          jdkFile: mandrel-${{ env.MANDREL_VERSION }}-17.tar.gz
          java-version: 17
          architecture: x64
          cache: maven

      - name: build-test-native
        run: ./mvnw -B clean verify -Pnative -Dquarkus.http.host=0.0.0.0

  native-container-build-test:
    runs-on: ubuntu-latest
    if: github.repository == 'edeandrea/how-about-some-tests'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: build-test-native-container
        run: |
          ./mvnw -B clean verify -Pnative \
            -Dquarkus.native.builder-image=${{ env.MANDREL_IMAGE }}:${{ env.MANDREL_VERSION }}-java17 \
            -Dquarkus.native.container-build=true \
            -Dquarkus.container-image.build=true \
            -Dquarkus.http.host=0.0.0.0